services:
  snet.framework.api:
    image: ${DOCKER_REGISTRY-}snetframeworkapi
    build:
      context: .
      dockerfile: src/SNET.Framework.Api/Dockerfile
    ports:
      - 8081:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire.dashboard:18889
    networks:
     - otel

  aspire.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
     - 18888:18888
    networks:
     - otel

networks:
  otel:

